name: pytorch
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - asn1crypto=1.3.0=py37_0
  - blas=1.0=mkl
  - ca-certificates=2020.1.1=0
  - certifi=2020.4.5.1=py37_0
  - cffi=1.14.0=py37h2e261b9_0
  - chardet=3.0.4=py37_1003
  - conda-package-handling=1.6.0=py37h7b6447c_0
  - cryptography=2.8=py37h1ba5d50_0
  - cudatoolkit=10.2.89=hfd86e86_1
  - cycler=0.10.0=py37_0
  - dbus=1.13.14=hb2f20db_0
  - expat=2.2.6=he6710b0_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - glib=2.63.1=h5a9c865_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - icu=58.2=he6710b0_3
  - idna=2.8=py37_0
  - intel-openmp=2020.1=217
  - joblib=0.15.1=py_0
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.2.0=py37hfd86e86_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_0
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - matplotlib=3.1.3=py37_0
  - matplotlib-base=3.1.3=py37hef1b27d_0
  - mkl=2020.1=217
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.0.15=py37ha843d7b_0
  - mkl_random=1.1.1=py37h0573a6f_0
  - mypy=0.770=py_0
  - mypy_extensions=0.4.3=py37_0
  - ncurses=6.2=he6710b0_0
  - ninja=1.9.0=py37hfd86e86_0
  - numpy=1.18.1=py37h4f9e942_0
  - numpy-base=1.18.1=py37hde5b4d6_1
  - olefile=0.46=py37_0
  - openssl=1.1.1g=h7b6447c_0
  - pandas=1.0.3=py37h0573a6f_0
  - pcre=8.43=he6710b0_0
  - pillow=7.1.2=py37hb39fc2d_0
  - pip=20.0.2=py37_1
  - psutil=5.7.0=py37h7b6447c_0
  - pycosat=0.6.3=py37h7b6447c_0
  - pycparser=2.19=py37_0
  - pyopenssl=19.1.0=py37_0
  - pyparsing=2.4.7=py_0
  - pyqt=5.9.2=py37h05f1152_2
  - pysocks=1.7.1=py37_0
  - python=3.7.6=h0371630_2
  - python-dateutil=2.8.1=py_0
  - pytorch=1.5.0=py3.7_cuda10.2.89_cudnn7.6.5_0
  - pytz=2020.1=py_0
  - qt=5.9.7=h5867ecd_1
  - readline=7.0=h7b6447c_5
  - requests=2.22.0=py37_1
  - rope=0.17.0=py_0
  - ruamel_yaml=0.15.87=py37h7b6447c_0
  - scikit-learn=0.22.1=py37hd81dba3_0
  - scipy=1.4.1=py37h0b6359f_0
  - setuptools=45.2.0=py37_0
  - sip=4.19.8=py37hf484d3e_0
  - six=1.14.0=py37_0
  - sqlite=3.31.1=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - tornado=6.0.4=py37h7b6447c_1
  - tqdm=4.42.1=py_0
  - typed-ast=1.4.1=py37h7b6447c_0
  - typing_extensions=3.7.4.1=py37_0
  - urllib3=1.25.8=py37_0
  - wheel=0.34.2=py37_0
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=had09818_2
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - click==7.1.2
    - configparser==5.0.0
    - docker-pycreds==0.4.0
    - future==0.18.2
    - gitdb==4.0.5
    - gitpython==3.1.2
    - gql==0.2.0
    - graphql-core==1.1
    - mypy-extensions==0.4.3
    - nvidia-ml-py3==7.352.0
    - pathtools==0.1.2
    - promise==2.3
    - pyyaml==5.3.1
    - sentry-sdk==0.14.4
    - shortuuid==1.0.1
    - simple-parsing==0.0.10.post3
    - smmap==3.0.4
    - subprocess32==3.5.4
    - torchvision==0.6.0
    - typing-extensions==3.7.4.2
    - typing-inspect==0.6.0
    - wandb==0.8.36
    - watchdog==0.10.2
prefix: /home/fabrice/miniconda3/envs/pytorch

